### ISSUE TITLE
create requirements file

### ISSUE THREAD

**Issue by bbelderbos** [Dabrien1/app2#4]
yes I can :)

```
$ python -m src PDM2.pst
Protein World  | SALE JUST GOT BIGGER!😮 | 2022-07-16 09:02:31
Postmates | Up to 45% off | Consider it a gift 🎁 | 2022-07-16 02:21:01
```

btw can you add a requirements.txt file? it seems one has to install `libpff-python` to get it running ...

_Originally posted by @bbelderbos in https://github.com/Dabrien1/app2/pull/3#discussion_r946709170_

**Comment by Dabrien1** [comment]
requirements.txt added

**Comment by bbelderbos** [comment]
Thanks!
