### ISSUE TITLE
write html file and open in browser

### ISSUE THREAD

**Issue by bbelderbos** [Dabrien1/app2#6]
Standard Library comes with `webbrowser` - https://twitter.com/bbelderbos/status/1552601127656595456

**Comment by Dabrien1** [comment]
Per code checkin this am, opting for output to txt file instead of web browser

**Comment by bbelderbos** [comment]
I think that's a good call. It was nice confirming it works with `start`+ my `open` = pretty universal solution. Not sure about Linux. Do you have a Linux to try it on?
